### ISSUE TITLE
Set local wine-label-app for testing API.

### ISSUE THREAD

**Issue by qjhart** [qjhart/wine-label-app#17]
Local application developers need to be able to access a more complete database of information to test their systems.  We need an example of how to do that.

**Comment by qjhart** [comment]
@pablodefendini , where the application goes for the API is set when you create the <wine-app>
https://github.com/qjhart/wine-label-app/blob/master/index.html#L106

Changing this to ```<wine-app  api="http://api.labels.qjhart.org"></wine-app>```

Will use the testing API for data.  This has all the labels, and catalogs and catalog pages.

**Comment by pablodefendini** [comment]
Perfect, thanks. I've got it working locally now. Still having issues on Safari vs Chrome, but they look like UI issues, so I'll track down on my end.
